# from GitHub, overriding the name and specifying a specific tag
- src: https://github.com/CoffeeITWorks/ansible-role-nagios.git
  version: master
  name: ansible-role-nagios

- src: geerlingguy.repo-epel

- src: coffeeitworks.ansible_nagios4_server_config

- src: coffeeitworks.ansible_nagios4_checkmk_livestatus
  version: 1.0.0
